### ISSUE TITLE
images/WidgetArch.png missing in part 2

### ISSUE THREAD

**Issue by Carreau** [jupyter/scipy-advanced-tutorial#11]
@jdfreder  ?

**Comment by jdfreder** [comment]
The notebook that uses this image was not actually used in the talk, I just included in the repository - just in case I needed more content.  

It actually lives here: https://github.com/ipython/ipython-in-depth/blob/master/examples/Interactive%20Widgets/Custom%20Widget%20-%20Hello%20World.ipynb

Along with said image:
https://github.com/ipython/ipython-in-depth/blob/master/examples/Interactive%20Widgets/images/WidgetArch.png
