### ISSUE TITLE
BLD,REF: make hello-scipy-full.js pip-installable with jupyter-pip

### ISSUE THREAD

**Issue by westurner** [jupyter/scipy-advanced-tutorial#14]
https://github.com/jupyter/scipy-advanced-tutorial/blob/master/Part1/extensions/hello-scipy-full.js

https://github.com/jdfreder/jupyter-pip

**Comment by westurner** [comment]
less the string constants and atob s

**Comment by Carreau** [comment]
No, Jupyter-pip is not the solution and this is a tutorial not only an extension.

**Comment by westurner** [comment]
(This functionality would be useful)

**Comment by rgbkrk** [comment]
You could always create your own extension with hello-scipy-full.js that uses jupyter-pip @westurner, under your own namespace.

**Comment by westurner** [comment]
Got it. Thanks!
